

# Barcode files:

bc1: "Round1_barcodes_new5.txt"
bc2: "Round2_barcodes_new4.txt"
bc3: "Round3_barcodes_new4.txt"

# FASTQ file of raw reads
raw_reads: "raw_fastq_small.fastq"


# path or URL to sample sheet (TSV format, columns: sample, condition, ...)
samples: samples.tsv
# path or URL to sequencing unit sheet (TSV format, columns: sample, unit, fq1, fq2,
# strandedness). Units are technical replicates (e.g. lanes, or resequencing of the
# same biological sample).If the column "strandedness" is present (which is optional),
# can be empty or has one of these values: none, yes or reverse. none is for unstranded
# protocols, yes an reverse follow the nomenclature used in `htseq-count --reverse`
# which is referenced in STAR manual section 7, "Counting number of reads per gene".

units: units.tsv

trimming:
  # skip trimming: false or true
  skip: false
  # the sequencing adapter
  adapter: ACGGATCGATCGATCGATCGAT

ref:
  # the STAR index
  index: "../STAR/ctat_genome_lib_build_dir/ref_genome.fa.star.idx"
  # gtf file with transcripts
  annotation: "../STAR/ctat_genome_lib_build_dir/ref_annot.gtf"
  fusion_index: "../STAR/ctat_genome_lib_build_dir"

star_fusion: false

pca:
  labels:
    # columns of sample sheet to use for PCA
    - condition

diffexp:
  # contrasts for the deseq2 results method
  contrasts:
    treated-vs-untreated:
      - treated
      - untreated

params:
  star: >
    --outReadsUnmapped None \
          --outSAMstrandField intronMotif \
          --outSAMunmapped Within \
          --chimSegmentMin 12 \
          --chimJunctionOverhangMin 12 \
          --chimOutJunctionFormat 1 \
          --alignSJDBoverhangMin 10 \
          --alignMatesGapMax 100000 \
          --alignIntronMax 100000 \
          --alignSJstitchMismatchNmax 5 -1 5 5 \
          --outSAMattrRGline ID:GRPundef \
          --chimMultimapScoreRange 3 \
          --chimScoreJunctionNonGTAG -4 \
          --chimMultimapNmax 20 \
          --chimNonchimScoreDropMin 10 \
          --peOverlapNbasesMin 12 \
          --peOverlapMMp 0.1 \
  cutadapt-se: ""
  cutadapt-pe: ""
